config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get 'signup' => 'users#new'

  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :questions, :only => [:create, :show, :index] do
    resources :answers, :only => [:create]
    resources :subscriptions, :only => [:create, :destroy]
  end

  get 'client' => 'subscriptions#client', as: 'client_js'
  get 'client_subscriptions' => 'subscriptions#client_subscriptions', as: 'subscription_js'

  get 'partials/notification/:notification_id' => 'partials#notification'

  get '/new' => 'questions#new', as: 'new_questions'
  get '/answered' => 'questions#answered', as: 'answered_questions'

  resources :users, except: :new do
    resources :subscriptions, :only => [:index]
  end

  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, :polymorphic => true

  belongs_to :sender, class: User
  belongs_to :reciever, class: User

  scope :recent, lambda{ |limit = 15|
    order( :created_at => :desc ).limit( limit )
  }

end

app/controllers/notifications_controller.rb
class NotificationsController < FayeRails::Controller

  observe Notification, :after_create do |new_notification|

    channel = "/notifications/#{new_notification.reciever_id}/#{new_notification.notifiable_id}"

    data = {
      notification: new_notification.attributes
    }
    
    NotificationsController.publish(channel, data)

  end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper


  def render_notification notification, locals={}
    defaults = {
      :main => :li,
      :sender => :span,
      :message => :span,
      :notifiable => :span,
      :html => {
        :class => 'notification',
        :data => {
          :resource => 'notification',
          :id => notification.id
        }
      }
    }
    
    render(partial: notification, locals: defaults.deep_merge(locals), layout: false)
  end

  def render_notification_list notifications, locals={}
    defaults = {
      :main => :ul,
      :notification => :li,
      :html => {
        :class => 'list'
      },
      :notifications => notifications
    }
    
    render('notifications/notification_list', defaults.deep_merge(locals))
  end


end

app/views/notifications/_notification.html.erb
<%= content_tag main, html do %>
    <%= content_tag sender, class: 'sender' do %>
      <%= link_to notification.sender.name + ' Answerd', user_path( notification.sender ) %>:
    <% end %>
    <br>
      <%= content_tag notifiable, class: 'notifiable' do %>
        <%= link_to notification.notifiable.content, question_path( notification.notifiable, notification_id: notification.id ) %>
      <% end %>
      <div class="line"></div>
      <%= content_tag message, class: 'message' do %>
        <%= link_to notification.message, question_path( notification.notifiable, notification_id: notification.id ) %>
      <% end %>
<% end %>

app/views/notifications/_notification_list.html.erb
<%= content_tag main, html do %>
  <% notifications.each do |n|%>
    <% unless n.viewed? %>
      <%= render_notification(n, main: notification) %>
    <% end %>
  <% end %>
<% end %>