config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get 'signup' => 'users#new'

  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :questions, :only => [:create, :show, :index] do
    resources :answers, :only => [:create]
    resources :subscriptions, :only => [:create, :destroy]
  end

  get 'client' => 'subscriptions#client', as: 'client_js'
  get 'client_subscriptions' => 'subscriptions#client_subscriptions', as: 'subscription_js'

  get 'partials/notification/:notification_id' => 'partials#notification'

  get '/new' => 'questions#new', as: 'new_questions'
  get '/answered' => 'questions#answered', as: 'answered_questions'

  resources :users, except: :new do
    resources :subscriptions, :only => [:index]
  end

  

end

app/views/shared/_authorized_header.html.erb
<div class='nav-wrapper'>
<ul id="nav">
  <%= content_tag :li, link_to("Hot", questions_path), class:active(questions_path) %>
  <%= content_tag :li, link_to("New", new_questions_path), class:active(new_questions_path) %>
  <%= content_tag :li, link_to("Answered", answered_questions_path), class:active(answered_questions_path) %>

</ul>    
    <!-- log out -->
<%= content_tag :ul, id: 'controls' do %>
  <%= content_tag :li do %>
    <%= render_notification_list(current_user.notifications.recent, html: { id: 'notification-list' }) %>
  <% end %>
  <%= content_tag :i, link_to('', '#', class: 'icon-bell-alt', id: 'notifications-button') %>
  <%= content_tag :i, link_to('', current_user, class:"icon-user") %>
  <%= content_tag :i, link_to('', signout_path, class: 'icon-logout', method: 'delete') %>
<% end %>
        <!-- notifications -->

app/views/shared/_footer.html.erb
<div class='footer'></div>
<% if user_signed_in? %>
  <ul id='question-queries'></ul>
  
  <footer>
  <!-- new question -->
  <%= render 'questions/form', question: current_user.questions.new, html: { } %>
  </footer>
<% end %>

app/views/shared/_header.html.erb
<header>

  <% if user_signed_in? %>
    
    <%= render 'shared/authorized_header' %>

  <% else %>

    <%= render 'shared/unauthorized_header' %>
    
  <% end %>
  
</header>

app/views/shared/_unauthorized_header.html.erb
<div class='nav-wrapper'>

<ul id="nav">
  <li class="active"><%= link_to "Explain.it", root_path %></li>
</ul> 
  <ul id="controls"> 
    <li>
      <%= render 'sessions/form' %>  
    </li>
  </ul>
</div>