config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get 'signup' => 'users#new'

  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :questions, :only => [:create, :show, :index] do
    resources :answers, :only => [:create]
    resources :subscriptions, :only => [:create, :destroy]
  end

  get 'client' => 'subscriptions#client', as: 'client_js'
  get 'client_subscriptions' => 'subscriptions#client_subscriptions', as: 'subscription_js'

  get 'partials/notification/:notification_id' => 'partials#notification'

  get '/new' => 'questions#new', as: 'new_questions'
  get '/answered' => 'questions#answered', as: 'answered_questions'

  resources :users, except: :new do
    resources :subscriptions, :only => [:index]
  end

  

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :question, counter_cache: :total_subscribers
  validates :user_id, :uniqueness => { :scope => :question_id }

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  authorize :user
  protect_from_forgery except: [:client, :client_subscriptions]

  before_action :set_subscription

  def create
    respond_to do |format|
      if @subscription.save
        format.js
        format.html { redirect_to question_path(@subscription.question) }
      else
        format.js { j(render 'shared/fail') }
        format.html
      end
    end
  end

  def destroy
    @subscription.destroy
    respond_to do |format|
      format.js { render :create }
      format.html { redirect_to question_path(@subscription.question) }
    end
  end

  def index
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.json { render json: Hash[@user.subscriptions.joins(:question).pluck(:question_id, :content)] }
    end
  end

  def client
    respond_to do |format|
      format.js
    end
  end

  def client_subscriptions
    respond_to do |format|
      format.js
    end
  end

  private
    def set_subscription
      @subscription = if id = params[:id]
                        current_user.subscriptions.find(id)
                      else
                        current_user.subscriptions.build(question_id: params[:question_id])
                      end
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_new.html.erb
<span class='subscription-count'>
<% if current_user.subscribed? question %>
  <%= link_to(image_tag("stared.png"), question_subscription_path(question, current_user.subscriptions.find_by_question_id( question.id )), :method => :delete, :remote => true) %>
<% else %>
  <%= link_to(image_tag("star.png"), question_subscriptions_path(question), :method => :post, :remote => true) %>
<% end %>
<span class='subscription-counter-<%= question.id %>'><%= question.subscriptions.count - 1 %></span>
</span>

app/views/subscriptions/_scripts.html.erb
<% if user_signed_in? %>
  <%= javascript_include_tag '/explained/client' %>
  <%= javascript_include_tag client_js_path %>
  <%= javascript_include_tag subscription_js_path %>
<% end %>

app/views/subscriptions/client.js.erb
window.EXPLAIN = {
  client: new Faye.Client( '/explained' ),
  subscriptions: {}
}

app/views/subscriptions/client_subscriptions.js.erb
(function(){
  var subscriptions;
  
  subscriptions = $.getJSON( '/users/<%= current_user.id %>/subscriptions', function( response ){
    var questionId,
        question;


    for( questionId in response ){
      question = response[ questionId ];

      window.EXPLAIN.subscriptions[ question ] = window.EXPLAIN.client.subscribe( '/notifications/<%= current_user.id %>/' + questionId , function( notification ){
        $( document ).trigger( 'notification', [ notification ] );
      });
    }
  });
  
}).call( this );

    

app/views/subscriptions/create.js.erb
(function(){
  var questionSelector     = "*[data-resource='question'][data-id='<%= @subscription.question.id %>']",
      thumbSelector        = ".thumb[data-resource='question-thumb'][data-id='<%= @subscription.question.id %>']",
      $question            = $( questionSelector ),
      $thumb               = $( thumbSelector ),
      newSubscriptionCount = $( '<%= j(render "subscriptions/new", question: @subscription.question) %>' ),
      tClone,
      qClone;

  tClone = newSubscriptionCount.clone().hide();
  qClone = newSubscriptionCount.clone().hide();
  $question.find('.subscription-count').fadeOut( 'fast', function(){
    $( this ).replaceWith( qClone );
    qClone.fadeIn( 'fast' );
  });

  // ( 'fast', function(){
  // });
  $thumb.find('.subscription-count').fadeOut( 'fast', function(){
    $( this ).replaceWith( tClone );
    tClone.fadeIn( 'fast' );
  });

}).call(this);